id: a3c52872fc0f4468b7801463bf01c66b
initial_creation_type: ocr
source_metadata:
  volumes:
    e17fc9b972a842e49051ba23e7a70bae:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: ''
      total_pages: 1902
      volume_number: 26
